name: Update NFL Data

on:
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes
  workflow_dispatch:         # allows manual trigger in Actions tab

permissions:
  contents: write            # ✅ allows pushes with GITHUB_TOKEN

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }} # ✅ expose secret to Node.js

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false   # ✅ we'll set up credentials manually

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run update-all
        run: npm run update-all

      - name: Configure Git and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add src/data/game/games.json src/data/player/scores.json src/data/player/picks.json src/data/player/last_updated.json
          git commit -m "Auto-update scores & picks [skip ci]" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}
